# Generated by Django 2.2.4 on 2020-12-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPL_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='style',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
