# Generated by Django 2.2.4 on 2020-12-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPL_app', '0002_lesson_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='lessons',
            field=models.ManyToManyField(related_name='lessons', through='TPL_app.Lesson', to='TPL_app.Teacher'),
        ),
    ]
