# Generated by Django 2.2.4 on 2020-12-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPL_app', '0003_auto_20201223_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
