# Generated by Django 2.2.4 on 2020-12-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPL_app', '0004_lesson_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
