# Generated by Django 2.2.4 on 2020-12-24 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TPL_app', '0006_auto_20201224_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TPL_app.Child'),
        ),
    ]
