# Generated by Django 2.2.4 on 2020-12-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPL_app', '0007_auto_20201224_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
