# Generated by Django 2.2.4 on 2020-12-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPL_app', '0010_auto_20201226_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='TPL_app/static/images/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='TPL_app/static/images/'),
        ),
    ]
