# Generated by Django 2.2.4 on 2020-12-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPL_app', '0011_auto_20201226_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='is_parent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_teacher',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
